### ISSUE TITLE
Enmascarar el ingreso de contrasenha

### ISSUE THREAD

**Issue by edgamen** [BictiaProyectoFinalFSJS/backEnd#2]
Seria conveniente ofuscar el ingreso de la contrasenha.

**Comment by zvala93** [comment]
Seria conveniente que ayudaras a programar en vez de simplemente escribir los errores que tenemos faltando menos de 2 horas para la entrega del proyecto...

**Comment by zvala93** [comment]
Adicionalmente este error ya fue solucionado en la versión actual.
